# -*- coding: utf-8 -*-
"""Task1 . Data Exploration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JEl4yHiasH1Zy3iMPl-hFXeG8wudtdti
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('Time_to_think_Norbury.csv', sep=';')
data.head()

data.shape

data.describe()

data.dtypes

data.isnull().sum() #there are no NAs

data['PSQI_component_1'].unique() #chech the outcome

data['psqi_2_groups'].unique() #chech the dichotomized outcome

#check correlations and distribution of the numeric variables with pairs graph:  
pair = sns.pairplot(data, vars=[ "MEQ", "Trait_Anxiety", "Avg_Weekly_Sleep_Duration",  "Avg_Sleep_Working_days", "Avg_sleep_free_days" , "Daytime_Dozing", "Age"  ])

#Check distribution of the main categorical variables:
categorical_features = ["University", "Sex", "Year_of_Study", "Department_Name", "Start_time", "Daytime_Dozing_Groups", "Cigarettes_dichotomous", "Alcohol_dichotomous", "Caffeine_dichotomous", "coffee_dichotomous", 'psqi_2_groups' ]
for col in data[categorical_features]:
    data[col].value_counts().sort_index(ascending=False).plot(kind="barh").set_title(col)
    plt.show()